version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  web:
    build: .
    ports:
     - "80:8888"
    volumes:
     - .:/sanda_test
    links:
     - db
    environment:
     - USER_ID=root
     - USER_PW=example
     - HOST_DB=db


