version: '2'
services:
  db:
    image: mariadb
    container_name: sqldb
    ports:
     - "3306:3306"
    volumes:
     - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  web:
    build: .
    ports:
     - "80:8888"
    volumes:
     - .:/sanda_test
    links:
     - db
    environment:
     - DB_HOST=db
     - DB_USER_ID=root
     - DB_USER_PW=example
     - DB_PORT=3306
     - DB_NAME=arrowdb

volumes:
    db_data:
